{
    "0.1.1": {
        "info": {
            "author": "\u6709\u5927\u5bb6\u79d1\u6280\u6709\u9650\u516c\u53f8",
            "author_email": "dev@funji.club",
            "bugtrack_url": null,
            "classifiers": [
                "Development Status :: 4 - Beta",
                "Environment :: Web Environment",
                "Intended Audience :: Developers",
                "License :: OSI Approved :: BSD License",
                "Operating System :: OS Independent",
                "Programming Language :: Python :: 3.9"
            ],
            "description": "# yoto_excpetion\n\nyoto_api\u7684\u5f02\u5e38\u7c7b\uff0c\u5305\u62ec\u9519\u8bef\u7801\u548c\u9519\u8bef\u63d0\u793a\n\n**\u8981\u6c42**: Python 3.9+\n\n---\n\n## \u9519\u8bef\u7801\n\n\u9519\u8bef\u7801\u6587\u6863\uff1a[\u9519\u8bef\u7801](https://funji.feishu.cn/docs/doccnbqSDQKvX0URRHg9rLnejY4#)\n\n---\n\n## \u66f4\u65b0pypi\u7684\u5305\n\n1\u3001\u751f\u6210wheel\u5305\n```\npython3 setup.py sdist bdist_wheel\n```\n2\u3001\u4e0a\u4f20wheel\u6587\u4ef6\n\n    \u8d26\u53f7\u5bc6\u7801\u53ef\u4ee5\u76f4\u63a5\u8f93\u5165\uff0c\u4e5f\u53ef\u4ee5\u751f\u6210\u4e00\u4e2a\u6587\u4ef6$HOME/.pypirc\uff0c\u5185\u5bb9\u5982\u4e0b\uff1a\n\n    [pypi]\n\n        username = __token__\n\n        password = pypi-AgEIcHlwaS5vcmcCJDk3MjE5MzdjLWEyYmMtNGI5OC05YmU3LTdmNzFkNjRiMjc3MgACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgBOxVPheoeWle95iQjr7l65chP_KbSrhVxze6o3S9AMA\n\n```\npython3 -m twine upload dist/*\n```\n\n## \u5b89\u88c5\n\n```shell\npip install -i https://test.pypi.org/simple/ yoto-exception\n```\n\n---\n\n## \u4f7f\u7528\n\n```\n    from yoto_excpetion import register_exception\n\n    from src.core.log import logger\n    from src.utils.common import alarm\n\n\n    def create_app(app: FastAPI):\n\n        ... \u6dfb\u52a0\u4e00\u4e9b\u64cd\u4f5c\u5728\u6355\u83b7\u5f02\u5e38\u4e4b\u524d\n\n        register_exception(app, logger, alarm)  # \u6ce8\u518c\u6355\u83b7\u5f02\u5e38\u4fe1\u606f\n\n        ... \u6dfb\u52a0\u4e00\u4e9b\u64cd\u4f5c\u5728\u6355\u83b7\u5f02\u5e38\u4e4b\u540e\n```\n\n\n",
            "description_content_type": "text/markdown",
            "docs_url": null,
            "download_url": "",
            "downloads": {
                "last_day": -1,
                "last_month": -1,
                "last_week": -1
            },
            "home_page": "https://gitlab.corp.funji.club/funji_dev/im/yoto_exception.git",
            "keywords": "",
            "license": "BSD",
            "maintainer": "",
            "maintainer_email": "",
            "name": "yoto-exception",
            "package_url": "https://pypi.org/project/yoto-exception/",
            "platform": "",
            "project_url": "https://pypi.org/project/yoto-exception/",
            "project_urls": {
                "Homepage": "https://gitlab.corp.funji.club/funji_dev/im/yoto_exception.git"
            },
            "release_url": "https://pypi.org/project/yoto-exception/0.1.1/",
            "requires_dist": null,
            "requires_python": ">=3.9",
            "summary": "yoto_api\u7684\u5f02\u5e38\u6a21\u5757",
            "version": "0.1.1",
            "yanked": false,
            "yanked_reason": null
        },
        "last_serial": 8669448,
        "urls": [
            {
                "comment_text": "",
                "digests": {
                    "md5": "a15f154a341df8077c7b9d3b6410786e",
                    "sha256": "5b0cb7a209b12c8c6bafe6df475ae06d29a2e5f08aa49b5039ea0af235e60080"
                },
                "downloads": -1,
                "filename": "yoto_exception-0.1.1-py3-none-any.whl",
                "has_sig": false,
                "md5_digest": "a15f154a341df8077c7b9d3b6410786e",
                "packagetype": "bdist_wheel",
                "python_version": "py3",
                "requires_python": ">=3.9",
                "size": 13301,
                "upload_time": "2020-11-16T11:30:18",
                "upload_time_iso_8601": "2020-11-16T11:30:18.141193Z",
                "url": "https://files.pythonhosted.org/packages/f5/5e/17e2e180b9f99ad8ec0846c37e9d0af20d2cdf37022b6a6593e9ec373586/yoto_exception-0.1.1-py3-none-any.whl",
                "yanked": false,
                "yanked_reason": null
            },
            {
                "comment_text": "",
                "digests": {
                    "md5": "e2fd8b02c33ab8f1522fb2ebca63c392",
                    "sha256": "cc78a0ebd02a5eafd3018fffe54ac70148d488738979317e09796a3955e3c4be"
                },
                "downloads": -1,
                "filename": "yoto_exception-0.1.1.tar.gz",
                "has_sig": false,
                "md5_digest": "e2fd8b02c33ab8f1522fb2ebca63c392",
                "packagetype": "sdist",
                "python_version": "source",
                "requires_python": ">=3.9",
                "size": 10537,
                "upload_time": "2020-11-16T11:30:19",
                "upload_time_iso_8601": "2020-11-16T11:30:19.277257Z",
                "url": "https://files.pythonhosted.org/packages/d2/4b/c3320b49fd3273639cbdb979995f7435c64911adc75ae9a8be134956d1f8/yoto_exception-0.1.1.tar.gz",
                "yanked": false,
                "yanked_reason": null
            }
        ],
        "vulnerabilities": []
    }
}